Use capitalised labels for instance types [WD-2877]
canonical/lxd-ui pull request #284
Opened 2023-04-11 12:37 UTC by lorumic

## Done

- Set capitalised labels for instance types throughout the app

Fixes [WD-2877](https://warthogs.atlassian.net/browse/WD-2877)

## QA

1. Run the LXD-UI:
    - On the demo server via the link posted by @webteam-app below. This is only available for PRs created by collaborators of the repo. Ask @lorumic or @edlerd for access.
    - With a local copy of this branch, run as described in the [Readme](https://github.com/canonical/lxd-ui#setting-up-for-development).
2. Perform the following QA steps:
    - Check labels for instance types in: instance list, instance side panel, instance detail page (overview), instance creation page (dropdown)

2023-04-11 12:37 UTC, webteam-app commented
Demo starting at https://lxd-ui-284.demos.haus

2023-04-11 13:55 UTC, al-bakalova commented
@lorumic This looks very good. Thank you!
The only dropdown that still needs an update is the filter in the "Select base image" modal. Can we please update it as part of this PR?

![Screenshot 2023-04-11 at 16 52 51](https://user-images.githubusercontent.com/114913788/231185067-c8d02d7c-3c21-4771-847f-e3671422bcf4.png)

2023-04-11 14:16 UTC, lorumic commented
> The only dropdown that still needs an update is the filter in the "Select base image" modal.

Ouch, I missed that one :) Should be good now.

2023-04-11 14:34 UTC, al-bakalova commented
@lorumic Looks good to me! Thanks for updating the dropdown options!

2023-04-12 10:20 UTC, edlerd requested changes

2023-04-12 10:20 UTC, edlerd commented on src/pages/instances/InstanceList.tsx
> +                  instanceCreationTypes.filter(
using `.find` should simplify this bit, it gives you the first match directly.

2023-04-12 10:34 UTC, edlerd approved these changes

2023-04-12 10:35 UTC, merged