Multi step iso selection
canonical/lxd-ui pull request #445
Opened 2023-09-01 07:35 UTC by edlerd

## Done

- extracted dedicated list for iso files when picking an image for the instance launch

## QA

1. Run the LXD-UI:
    - On the demo server via the link posted by @webteam-app below. This is only available for PRs created by collaborators of the repo. Ask @lorumic or @edlerd for access.
    - With a local copy of this branch, run as described [here](../HACKING.md#setting-up-for-development).
2. Perform the following QA steps:
    - create instance > browse images > use custom iso > upload custom iso
    - ensure the instance creation flow with uploading or selecting a custom iso file works flawless

2023-09-01 07:35 UTC, webteam-app commented
Demo starting at https://lxd-ui-445.demos.haus

2023-09-06 08:10 UTC, lorumic commented on src/pages/images/IsoSelector.tsx
> +          ),
![Screenshot from 2023-09-06 09:38:26](https://github.com/canonical/lxd-ui/assets/56583786/116452d4-54bd-413b-ba89-60c12d8496d6)

My gut feeling tells me that users would appreciate a delete button to get rid of ISOs much more here than where it is now (hidden in the storage pool detail page, volumes tab). I suggest to have it in both places: we could add just a delete icon at the end of the row, after the "Select" button.

2023-09-06 14:18 UTC, edlerd commented on src/pages/images/ImageSelectorModal.tsx
>        )}
On the first interaction with an empty list, we want to make it clear the iso is available later as well and not just for the one instance. That's why we always go to the select list - before and after uploading from the instance creation.

2023-09-06 14:24 UTC, edlerd commented
Changed the behaviour of the selection a bit, so now we have a choice between image and ISO before opening the modal on instance launch.

2023-09-07 08:02 UTC, lorumic reviewed
I like the way this is going. I think branching at the instance creation form stage is a good idea.
A few comments for some minor improvements follow.

2023-09-07 08:04 UTC, lorumic commented
The 2 comments about the `appearance` and `caption` props apply also to the `SelectImageBtn` component.

2023-09-07 08:09 UTC, edlerd commented on src/pages/images/CustomIsoSelectorModal.tsx
> +}
It is also used in `CustomIsoSelector`, but I'll put this in a type file and not have it next to the component.

2023-09-07 08:11 UTC, edlerd commented on src/pages/images/actions/SelectCustomIsoBtn.tsx
> +        <span>{caption}</span>
yes, the usages have changed so we can fixate the captions and appearances.

2023-09-07 09:01 UTC, edlerd commented
Thanks for the comments @lorumic I cleaned up the code according to your suggestions and adjusted the modal sizing to be more stable.

2023-09-07 09:04 UTC, edlerd commented on src/pages/images/ImageSelectorModal.tsx
>        )}
Yes, that should be less changy when switching the modals. I add some css for a more stable size.

2023-09-07 09:06 UTC, lorumic commented on src/pages/images/ImageSelectorModal.tsx
>        )}
I think the footer is supposed to stick to the bottom here, right?

![image](https://github.com/canonical/lxd-ui/assets/56583786/3e65223e-94d1-4952-b6c1-88b6edfef72d)

2023-09-07 09:09 UTC, lorumic commented on src/pages/images/actions/UseCustomIsoBtn.tsx
>          className="image-btn"
Is this class needed? Seems unused to me.

2023-09-07 09:09 UTC, lorumic commented on src/pages/images/actions/SelectImageBtn.tsx
>          className="image-btn"
Same as above.

2023-09-07 09:24 UTC, edlerd commented on src/pages/images/ImageSelectorModal.tsx
>        )}
right, I gave the table a wrapper with a min-height to have the footer pushed to the bottom of the modal.

2023-09-07 09:51 UTC, lorumic approved these changes
Thanks for applying the changes. It looks all good from a code and QA perspective.

2023-09-08 15:35 UTC, piperdeck requested changes
# 1

I can definitely see Michele's point about the empty ISO list creating an unnecessary click for the user. As discussed this morning, having a populated list here tested well in a user session yesterday. I think it's probably worth testing the empty list with a couple more users. I'm open to the idea of skipping this modal when the list is empty, but I'd like to see what users think of it first.

My vote is to leave it as-is for now, and revisit the topic with some user feedback in-hand.

## 2

This button can probably be set to the primary state, at least when the ISO list is empty.

![Pasted image 20230908112827](https://github.com/canonical/lxd-ui/assets/45367207/7f5d180b-5cde-47df-84e9-c8574e9b4108)

2023-09-08 16:22 UTC, edlerd commented
Thanks for the good suggestions @lorumic and @piperdeck . Making the upload primary in the empty ISO list makes a lot of sense, just pushed a change for that.

2023-09-08 17:01 UTC, piperdeck approved these changes
Looks good, approving!

2023-09-08 17:23 UTC, merged