Ensure correct type is set when creating an instance from a cached image
canonical/lxd-ui pull request #518
Opened 2023-11-01 09:53 UTC by lorumic

## Done

- Passed the correct image type when creating an instance from a cached image

## QA

1. Run the LXD-UI:
    - On the demo server via the link posted by @webteam-app below. This is only available for PRs created by collaborators of the repo. Ask @lorumic or @edlerd for access.
    - With a local copy of this branch, run as described [here](../HACKING.md#setting-up-for-development).
2. Perform the following QA steps:
    - Go to storage page, select "Cached images" tab
    - Click on the "Play" button to create an instance using a VM cached image (if you don't have one, first create a VM instance following the regular instance creation flow from the instances page)
    - Check that, on the instance creation page, the correct image type is selected in the (disabled) dropdown

2023-11-01 09:53 UTC, webteam-app commented
Demo starting at https://lxd-ui-518.demos.haus

2023-11-13 09:01 UTC, edlerd requested changes
This breaks the image selector in some cases it sets instance type to "any":
1. Create instance
2. Browse images
3. Select Type VM
4. Select Type Any
5. Choose the 1st image in the list
6. Create
7. Error appears: "Instance creation failed / Invalid instance type"

2023-11-13 11:01 UTC, lorumic commented
> This breaks the image selector in some cases it sets instance type to "any":
> 
> 1. Create instance
> 2. Browse images
> 3. Select Type VM
> 4. Select Type Any
> 5. Choose the 1st image in the list
> 6. Create
> 7. Error appears: "Instance creation failed / Invalid instance type"

I cannot reproduce this and I am not even sure I understood correctly these steps. Please add a screen capture or a clearer description of the steps.

2023-11-13 11:13 UTC, edlerd commented
Did you forget to push the update @lorumic ? The [problem described above is](https://github.com/canonical/lxd-ui/pull/518#pullrequestreview-1726811016) unchanged.

2023-11-13 11:15 UTC, lorumic commented
> Did you forget to push the update @lorumic ? The [problem described above is](https://github.com/canonical/lxd-ui/pull/518#pullrequestreview-1726811016) unchanged.

No, I didn't find any solution yet. I had a hard time reproducing it and was asking for further clarifications, but then I could reproduce it and deleted my message. I cannot undo the re-request of review though.

2023-11-13 11:41 UTC, lorumic commented
> This breaks the image selector in some cases it sets instance type to "any":

Should be fixed now.

2023-11-13 12:29 UTC, edlerd approved these changes
LGTM, thanks for the fixes, two minor suggestions below to improve code.

2023-11-13 12:29 UTC, edlerd commented on src/pages/images/ImageSelector.tsx
> +                  v.target.value === "any"
We should use the `ANY` constant to allow finding references.

2023-11-13 12:29 UTC, edlerd commented on src/pages/images/ImageSelector.tsx
> +              value={String(type ?? "")}
We can omit the String coercion here and simplify to `value={type ?? ""}`

2023-11-13 13:54 UTC, merged