[WD-11261] Implementation of LXD PWA with a dynamic start_url
canonical/lxd-ui pull request #785
Opened 2024-05-28 14:00 UTC by Kxiru

## Done

- Implemented minimal PWA support for the LXD-UI client in index.html.
    - The manifest file/variable supports a dynamic start_url link.
- Added a Logo image for the minimum requirements of the PWA.
- Added a LXD-Screenshot image for the minimum requirements of the PWA.

## QA

1. Run the LXD-UI:
    - On the demo server via the link posted by @webteam-app below. This is only available for PRs created by collaborators of the repo. Ask @mas-who or @edlerd for access.
    - With a local copy of this branch, run as described [here](../HACKING.md#setting-up-for-development).
2. Perform the following QA steps:
    - Open the LXD-UI Client and note the PWA pop up, or, view the 
![image](https://github.com/canonical/lxd-ui/assets/58699506/5ce64690-6b0e-40f4-9015-3f8d19888230)
--icon in the url toolbar. One can click this to trigger the installation sequence.

## Screenshots
![image](https://github.com/canonical/lxd-ui/assets/58699506/e32fb7ec-51b9-4c1b-a7b0-91376f071b77)
![image](https://github.com/canonical/lxd-ui/assets/58699506/a29df56c-3633-40a4-8f6f-d48d606c3a15)
![image](https://github.com/canonical/lxd-ui/assets/58699506/b54a73a3-e95e-40ce-bde5-4d0b12babae3)

2024-05-28 14:00 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://lxd-ui-785.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/14286)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-05-28 16:33 UTC, edlerd commented on index.html
> +    "scope": "/",
```suggestion
    "scope": window.location.origin,
```
I think this should also be the main url.

2024-05-28 16:34 UTC, edlerd commented on index.html
Please keep the previous formatting for the unchanged lines.

2024-05-30 07:59 UTC, mas-who commented
@Kxiru I think David has covered all the points. After making the changes for the screenshot reference path, it should work on the demo server as well.

In case if you are wondering why the path should be changed, you can go to the Source tab in your chrome inspector (see below for reference)

![Screenshot from 2024-05-30 09-57-49](https://github.com/canonical/lxd-ui/assets/151511568/10f55ca6-d0c2-4a88-bf6c-f07508d3b734)

2024-06-04 06:11 UTC, edlerd requested changes
The paths to the assets need to be prefixed with `/ui` and the scope field needs fixing.

I am not sure the orange menu bar is the best option, it seems a rather busy colour for it. Maybe use the grey/black from the left-hand navigation, or consult with design for this.

2024-06-04 06:11 UTC, edlerd commented on index.html
> +  var screenshot = window.location.origin + "/assets/img/";
```suggestion
  var screenshot = window.location.origin + "/ui/assets/img/";
```
This needs to be under the ui route.

2024-06-04 14:27 UTC, edlerd requested changes
It works on localhost, but not yet on the demo server -- and I fear it won't work in the real build either. See comments below.

2024-06-04 21:29 UTC, Kxiru commented
@edlerd , I've got it to work on the demo server and I've tidied up index.html a bit too :).

2024-06-05 10:05 UTC, edlerd reviewed
This works great on the demo server with signed certificates!
I found some small improvements that should be done before merging it.

2024-06-05 15:49 UTC, merged