[WD-11691] chore: minor UI change for vertical navigation resizing.
canonical/lxd-ui pull request #797
Opened 2024-06-14 01:17 UTC by Kxiru

## Done

- Minor scss changes to achieve the design stated in (this figma sheet)[https://www.figma.com/design/t01jtaUMluSUP5fE5n4KzE/Navbar-Login-Status?node-id=0-1&t=xbuuiuOi0wtFyqty-0]

## QA

1. Run the LXD-UI:
    - On the demo server via the link posted by @webteam-app below. This is only available for PRs created by collaborators of the repo. Ask @mas-who or @edlerd for access.
    - With a local copy of this branch, run as described [here](../HACKING.md#setting-up-for-development).
2. Perform the following QA steps:
    - N/A

## Screenshots

![image](https://github.com/canonical/lxd-ui/assets/58699506/94eb2d10-a7a8-4da6-a3c1-d4cd8c7f9d50)

![image](https://github.com/canonical/lxd-ui/assets/58699506/0847981a-7c87-41b1-8f50-eff9bb26d74a)

2024-06-14 01:17 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://lxd-ui-797.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/312)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-06-14 06:04 UTC, edlerd requested changes
We shouldn't introduce a new concept for scrolling. We currently have [this function](https://github.com/canonical/lxd-ui/blob/main/src/components/Navigation.tsx#L89) to set the lower part of the nav to scroll. It works by measuring its height and comparing it to the total available height. This way we get a smooth transition on resize of the browser. It should also work by enabling scrolling on collapse/un-collapse of the accordions in the navigation (like for storage) in all possible height/width combinations.

So either remove that function and find a pure css solution or remove the css solution and rely on the existing one.

2024-06-14 06:04 UTC, edlerd commented on src/sass/_pattern_navigation.scss
> +
```suggestion
```
We should never hide the scrollbar, as users with those browsers expect it to be present.

2024-06-18 08:12 UTC, edlerd requested changes
See screen below:

1. We shouldn't hide the scrollbar in the navigation (see scrollbar is present on the right)
2. The top part of the nav is cut, even though there is enough space below. The height of the top part should be fully responsive, so it works in all possible screen widths/heights perfectly.

![image](https://github.com/canonical/lxd-ui/assets/1155472/b54b00b1-12bd-4344-b341-fae7a82930ef)

2024-06-19 15:12 UTC, edlerd requested changes
On the demo server, the navigation doesn't scroll any more. I.e. when I shrink the browser windows height the lower part of the nav stays visible as required, but the middle part is cur with no way of reaching the hidden nav items. Is the demo not updated, or is it a problem with the changes?

2024-06-19 15:27 UTC, Kxiru commented
That being said, I have found that the top container is not scrollable. I added a fixing line for this in my last commit.

2024-06-19 15:41 UTC, edlerd requested changes
QA looks good now, the linter has some errors, see below.

2024-06-19 19:25 UTC, edlerd approved these changes
This looks good, nice work :+1:

2024-06-24 20:19 UTC, piperdeck approved these changes
LGTM

2024-06-25 06:40 UTC, merged