chore: Adjusted detail page titles for better ux consistency [WD-11696]
canonical/lxd-ui pull request #803
Opened 2024-06-20 17:06 UTC by Kxiru

## Done
- Created and adjusted scss classes.

## QA

1. Run the LXD-UI:
    - On the demo server via the link posted by @webteam-app below. This is only available for PRs created by collaborators of the repo. Ask @mas-who or @edlerd for access.
    - With a local copy of this branch, [build and run as described in the docs](../CONTRIBUTING.md#setting-up-for-development).
2. Perform the following QA steps:
    - Verify seamless visual difference between a parent page title and a child page title.

## Screenshots

![image](https://github.com/canonical/lxd-ui/assets/58699506/bccc811a-b595-4b5a-b49c-245e7c14a0b6)

![image](https://github.com/canonical/lxd-ui/assets/58699506/50e69b0d-f53c-4998-8373-2cc5a993aeca)

2024-06-21 06:57 UTC, edlerd commented
Demo: https://lxd-ui-803.demos.haus/

2024-06-21 07:05 UTC, edlerd requested changes
Thanks for the change, this is much better than before.

I found two issues on QA

1. The rename case is duplicating the "/" 
![Screenshot from 2024-06-21 08-59-42](https://github.com/canonical/lxd-ui/assets/1155472/7d9adffe-ed1e-4e47-aa77-acb5a9beb8f4)

2. This was broken before, I just realized it now due to focus on the header: The loading behaviour of the instance and profile detail pages render the header briefly without the prefix. This is causing a jump in the UI, maybe we can change the loading behaviour to immediately render with the prefix? Also for invalid instance names we should render the header with prefix, currently the bare name is rendered:

![Screenshot from 2024-06-21 08-59-54](https://github.com/canonical/lxd-ui/assets/1155472/305fe67c-16c8-40c7-bd01-e1d74d4dbe63)


![Screenshot from 2024-06-21 08-59-58](https://github.com/canonical/lxd-ui/assets/1155472/c8ad47e7-ce7c-4de4-96d8-e11bc87ac119)

![image](https://github.com/canonical/lxd-ui/assets/1155472/22844f31-3fe9-4175-b327-6c6b1f1101e6)

2024-06-21 11:23 UTC, edlerd requested changes
Thanks for the improvements, I can confirm all previous issues are resolved.

There is something odd with the rename case: The rename form is not correctly positioned 

![image](https://github.com/canonical/lxd-ui/assets/1155472/1887e304-4f0f-4afd-9265-a885eafd94e3)

2024-06-24 14:28 UTC, edlerd reviewed
QA and code looks good, thanks for improving this.

There is one glitch, which existed previously, about spacing. I think adding the suggested classes will fix it: When in a screen with low height and going into the rename mode, previously the height of the header would grow, causing an additional scrollbar to appear. With the changes I am to keep the height unchanged.

2024-06-24 14:28 UTC, edlerd commented on src/components/RenameHeader.tsx
> +                    className="cancel"
```suggestion
                    className="cancel u-no-margin--bottom"
```

2024-06-24 14:28 UTC, edlerd commented on src/components/RenameHeader.tsx
> +                    loading={formik.isSubmitting}
```suggestion
                    className="u-no-margin--bottom"
                    loading={formik.isSubmitting}
```

2024-06-24 14:28 UTC, edlerd commented on src/components/RenameHeader.tsx
> +                  className="name-input"
```suggestion
                  className="name-input u-no-margin--bottom"
```

2024-06-24 17:12 UTC, Kxiru commented
@edlerd , I added the ```window.dispatchEvent(new Event("resize"));``` function to enableRename() as discussed on Mattermost.

2024-06-24 20:16 UTC, piperdeck commented
looking good, nice job on this!

2024-06-24 20:17 UTC, piperdeck approved these changes
LGTM

2024-06-25 06:20 UTC, edlerd approved these changes
LGTM, thanks for improving the headers.

2024-06-25 06:21 UTC, merged